! This program aims to get the Wannier Centre from the .wout file generated by Wannier90
program WFcentre

      implicit none
      real, dimension(3) :: WF_center, Spread
      real, allocatable :: WF_spread(:)
      integer :: ios=0, nlines = 0, num_wann, i, Sequence_num_wann
      logical :: WFcentrefound = .FALSE., F
      character(len=30) :: filename, bracket1, bracket2, comma1, comma2,dummy, dummy1, dummy2
      character(len=200):: inline1, inline2, inline3

      print *, 'Input the filename'
      read *, filename

      print *, 'Input the Num_wann'
      read *, num_wann

      inquire(file=filename,exist=F)
      if(F) then
            open(unit=1,file=filename,status='OLD')
            print *, "Find the ", filename, "file successfully"
      else
            print *, "The file doesn't exist"
            STOP
      end if

      rewind(1)

      do while(ios==0)
            read(1,'(A)',iostat=ios) inline1             !'(A)' read the whole line
            inline2 = adjustl(trim(inline1))
            nlines = nlines + 1
            if(inline2=='Final State') then
                  WFcentrefound=.True.
                 EXIT
            end if
      end do

      if(WFcentrefound) then
            print *, "At the ",nlines, "line"
      else
            nlines = nlines - 1
            print *, "We don't find the Syntax"
      end if

      open(unit=2, file = 'WF_centerpp.dat')
      write(2,*) 'The following section contains Wannier Centers from .wout'

      do i = 1,num_wann
            read(1,'(a25,i3,a2,f10.6,a1,f10.6,a1,f10.6,a2)') inline1, Sequence_num_wann, bracket1,&
            WF_center(1),dummy1,WF_center(2), dummy2,WF_center(3), bracket2
            write(2,'(2x, f10.6, 2x f10.6, 2x, f10.6)') WF_center(1), WF_center(2), WF_center(3)
      end do

end program WFcentre
